package Examen1_ProgramacionII;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Scanner;
import javax.swing.JComboBox;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class MuelleSwing extends javax.swing.JFrame {

    private ArrayList<Barco> barcos;
    private String tipoCarga, barcoLabel, nombreAgregar;
    private int limitePasajeros;
    private double precioBoleto;
    private BarcoPesquero barcoPesquero;
    private BarcoPasajero barcoPasajero;
    public static Muelle muelle = new Muelle();

    public MuelleSwing() {
        barcos = new ArrayList<>();

        initComponents();
        MenuPrincipal.setVisible(true);
        AgregarBarco.setVisible(false);
        AgregarElemento.setVisible(false);
        VaciarBarco.setVisible(false);
        BarcosPorFecha.setVisible(false);

        DefaultComboBoxModel<String> añosModel = new DefaultComboBoxModel<>();
        Calendar calendar = Calendar.getInstance();
        for (int indice = 2024; indice <= 2034; indice++) {
            añosModel.addElement(String.valueOf(indice));
        }
        jComboBox3.setModel(añosModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        MenuPrincipal = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AgregarBarco = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        AgregarElemento = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        VaciarBarco = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        BarcosPorFecha = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 470));
        setMinimumSize(new java.awt.Dimension(720, 470));

        jPanel.setBackground(new java.awt.Color(255, 153, 255));
        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuPrincipal.setBackground(new java.awt.Color(255, 153, 255));
        MenuPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setBackground(new java.awt.Color(153, 0, 153));
        jButton5.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("SALIR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        MenuPrincipal.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 280, 50));

        jButton4.setBackground(new java.awt.Color(153, 0, 153));
        jButton4.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("BARCOS POR FECHA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        MenuPrincipal.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 280, 50));

        jButton3.setBackground(new java.awt.Color(153, 0, 153));
        jButton3.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("VACIAR BARCO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        MenuPrincipal.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 280, 50));

        jButton2.setBackground(new java.awt.Color(153, 0, 153));
        jButton2.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("AGREGAR ELEMENTO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        MenuPrincipal.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 280, 50));

        jButton1.setBackground(new java.awt.Color(153, 0, 153));
        jButton1.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("AGREGAR BARCO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        MenuPrincipal.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 280, 50));

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENÚ PRINCIPAL");
        MenuPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, -1, -1));

        jPanel.add(MenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 470));

        AgregarBarco.setBackground(new java.awt.Color(255, 204, 255));
        AgregarBarco.setMaximumSize(new java.awt.Dimension(720, 470));
        AgregarBarco.setMinimumSize(new java.awt.Dimension(720, 470));
        AgregarBarco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setBackground(new java.awt.Color(153, 0, 153));
        jButton10.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("AGREGAR");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        AgregarBarco.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 140, 40));

        jButton6.setBackground(new java.awt.Color(153, 0, 153));
        jButton6.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("REGRESAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        AgregarBarco.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 140, 40));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(0, 0, 0));
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });
        AgregarBarco.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 160, -1));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 0));
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });
        AgregarBarco.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 110, -1));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PRECIO DEL BOLETO:");
        AgregarBarco.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TIPOS:");
        AgregarBarco.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("AGREGAR BARCO");
        AgregarBarco.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jComboBox2.setBackground(new java.awt.Color(153, 0, 153));
        jComboBox2.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PEZ", "CAMARON", "LANGOSTA" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        AgregarBarco.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 190, -1));

        jComboBox1.setBackground(new java.awt.Color(153, 0, 153));
        jComboBox1.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "‏‏‎ ‎", "PESQUERO", "PASAJERO" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        AgregarBarco.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 190, -1));

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TIPO DE BARCO:");
        AgregarBarco.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        AgregarBarco.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 160, -1));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NOMBRE DEL BARCO:");
        AgregarBarco.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CANTIDAD DE PASAJEROS:");
        AgregarBarco.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jPanel.add(AgregarBarco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 470));

        AgregarElemento.setBackground(new java.awt.Color(255, 204, 255));
        AgregarElemento.setMaximumSize(new java.awt.Dimension(720, 470));
        AgregarElemento.setMinimumSize(new java.awt.Dimension(720, 470));
        AgregarElemento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setBackground(new java.awt.Color(153, 0, 153));
        jButton11.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("AGREGAR");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        AgregarElemento.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 140, 40));

        jButton7.setBackground(new java.awt.Color(153, 0, 153));
        jButton7.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("REGRESAR");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        AgregarElemento.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 140, 40));

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("NOMBRE DEL BARCO:");
        AgregarElemento.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("AGREGAR ELEMENTO");
        AgregarElemento.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(0, 0, 0));
        AgregarElemento.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 200, -1));

        jPanel.add(AgregarElemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 470));

        VaciarBarco.setBackground(new java.awt.Color(255, 204, 255));
        VaciarBarco.setMaximumSize(new java.awt.Dimension(720, 470));
        VaciarBarco.setMinimumSize(new java.awt.Dimension(720, 470));
        VaciarBarco.setPreferredSize(new java.awt.Dimension(720, 470));
        VaciarBarco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton8.setBackground(new java.awt.Color(153, 0, 153));
        jButton8.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("REGRESAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        VaciarBarco.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 140, 40));

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("VACIAR BARCO");
        VaciarBarco.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("TOTAL GENERADO");
        VaciarBarco.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(0, 0, 0));
        VaciarBarco.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 200, -1));

        jButton12.setBackground(new java.awt.Color(153, 0, 153));
        jButton12.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("VACIAR");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        VaciarBarco.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 140, 40));

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("NOMBRE DEL BARCO:");
        VaciarBarco.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        VaciarBarco.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 160, 40));

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        VaciarBarco.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 180, 40));

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("TIPO DE BARCO");
        VaciarBarco.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));

        jScrollPane1.setBackground(new java.awt.Color(153, 0, 153));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(153, 0, 153));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );

        VaciarBarco.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 400, 170));

        jPanel.add(VaciarBarco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 470));

        BarcosPorFecha.setBackground(new java.awt.Color(255, 204, 255));
        BarcosPorFecha.setMaximumSize(new java.awt.Dimension(720, 470));
        BarcosPorFecha.setMinimumSize(new java.awt.Dimension(720, 470));
        BarcosPorFecha.setPreferredSize(new java.awt.Dimension(720, 470));
        BarcosPorFecha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton13.setBackground(new java.awt.Color(153, 0, 153));
        jButton13.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("BUSCAR");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        BarcosPorFecha.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 140, 40));

        jButton9.setBackground(new java.awt.Color(153, 0, 153));
        jButton9.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("REGRESAR");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        BarcosPorFecha.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 140, 40));

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("BUSCAR BARCOS");
        BarcosPorFecha.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel17.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("ELIJA LA FECHA:");
        BarcosPorFecha.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jComboBox3.setBackground(new java.awt.Color(153, 0, 153));
        jComboBox3.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " ", " " }));
        BarcosPorFecha.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 160, -1));

        jTextArea2.setBackground(new java.awt.Color(153, 0, 153));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        BarcosPorFecha.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 670, 180));

        jPanel.add(BarcosPorFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AgregarBarco.setVisible(true);
        jComboBox1.setSelectedIndex(0);
        MenuPrincipal.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String nombre = JOptionPane.showInputDialog(null, "Ingrese el nombre del barco: ", "Agregar Elemento", JOptionPane.OK_CANCEL_OPTION);

        if (nombre.isBlank() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete el campo de Nombre.", "Campo Incompleto", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!nombre.isBlank() || !nombre.isEmpty()) {
            muelle.agregarElemento(nombre);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        VaciarBarco.setVisible(true);
        MenuPrincipal.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        BarcosPorFecha.setVisible(true);
        MenuPrincipal.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        AgregarBarco.setVisible(false);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        MenuPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        AgregarElemento.setVisible(false);
        MenuPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        VaciarBarco.setVisible(false);
        jTextArea1.setText("");
        jLabel13.setText("");
        jLabel14.setText("");
        jTextField5.setText("");
        MenuPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        BarcosPorFecha.setVisible(false);
        MenuPrincipal.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        String tipoBarco = jComboBox1.getSelectedItem().toString();
        String nombre;

        if (tipoBarco.equals("PESQUERO")) {
            nombre = jTextField1.getText();
            muelle.setTipoCarga(jComboBox2.getSelectedItem().toString().toString().toUpperCase());
            muelle.setNombreAgregar(nombre);
            muelle.agregarBarco(tipoBarco);
        } else if (tipoBarco.equals("PASAJERO")) {
            nombre = jTextField1.getText();
            int limitePasajeros = Integer.parseInt(jTextField2.getText());
            double precioBoleto = Double.parseDouble(jTextField3.getText());
            muelle.setLimitePasajeros(limitePasajeros);
            muelle.setPrecioBoleto(precioBoleto);
            muelle.setNombreAgregar(nombre);
            muelle.agregarBarco(tipoBarco);
        }

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedItem().toString().equals("‏‏‎ ‎")) {
            jLabel2.setVisible(false);
            jTextField1.setVisible(false);
            jLabel2.setVisible(false);
            jComboBox2.setVisible(false);
            jTextField2.setVisible(false);
            jLabel6.setVisible(false);
            jTextField3.setVisible(false);
            jLabel7.setVisible(false);
            jLabel5.setVisible(false);
        } else if (jComboBox1.getSelectedItem().toString().equals("PESQUERO")) {
            jLabel2.setVisible(true);
            jTextField1.setVisible(true);
            jComboBox2.setVisible(true);
            jLabel5.setVisible(true);
            jTextField2.setVisible(false);
            jLabel6.setVisible(false);
            jTextField3.setVisible(false);
            jLabel7.setVisible(false);
        } else if (jComboBox1.getSelectedItem().toString().equals("PASAJERO")) {
            jLabel2.setVisible(true);
            jLabel5.setVisible(true);
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jLabel6.setVisible(true);
            jTextField3.setVisible(true);
            jLabel7.setVisible(true);
            jLabel2.setVisible(false);
            jComboBox2.setVisible(false);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        int tecla = evt.getKeyChar();
        boolean valido = tecla >= 48 && tecla <= 57;
        if (!valido) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
        int tecla = evt.getKeyChar();
        boolean valido = tecla >= 48 && tecla <= 57 || tecla == 46;
        if (!valido) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField3KeyTyped

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        String nombre = jTextField5.getText();

        if (nombre.isBlank() || nombre.isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡Se necesita rellenar el dato del Nombre del Barco!", "Campo Incompleto", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (!nombre.isBlank() || !nombre.isEmpty()) {
            muelle.buscarBarco(nombre);
            jLabel13.setText(muelle.getBarcoLabel());

            if (muelle.getBarcoLabel().equalsIgnoreCase("PASAJERO")) {
                jTextArea1.setText("DATOS DEL BARCO: \n" + muelle.getBarcoPasajero().toString() + "\n\nLISTA DE PASAJEROS: \n" + muelle.getBarcoPasajero().listarPasajeros());
            } else if (muelle.getBarcoLabel().equalsIgnoreCase("PESQUERO")) {
                jTextArea1.setText("DATOS DEL BARCO: \n" + muelle.getBarcoPesquero().toString());
            }

            double total = muelle.vaciarBarco(nombre);
            jLabel14.setText("LPS. " + String.valueOf(total));
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        int fecha = Integer.parseInt(jComboBox3.getSelectedItem().toString());

        String mostrar = muelle.barcosDesde(fecha);

        if (mostrar == null) {
            jTextArea2.setText("NO SE ENCONTRARON BARCOS");
        } else {
            jTextArea2.setText("LISTA DE BARCOS: \n" + mostrar);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MuelleSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MuelleSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MuelleSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MuelleSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MuelleSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AgregarBarco;
    private javax.swing.JPanel AgregarElemento;
    private javax.swing.JPanel BarcosPorFecha;
    private javax.swing.JPanel MenuPrincipal;
    private javax.swing.JPanel VaciarBarco;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
